---
output: 
  pdf_document:
    keep_tex: false
    fig_caption: yes
    latex_engine: pdflatex
    template: theme/latexTemplate_qc.tex
geometry: margin=0.7in
papersize: letterpaper


report: true
author: "Laboratorio diagnóstico SaR-CoV-2"
date: "`r Sys.time()`"

plate: "`r plate`"
controls: "`r qcplate`"
ncontrols: "`r length(result_table$sample)`"

email: "juan@perez.gob.mx"
web: "www.laboratorio.gob.mx"


fontfamily: fontenc
fontsize: 11pt
header-includes:
   - \linespread{1.05}
graphics: true
width: 1
logoposition: center
logo: theme/Inmegenlogosalud.pdf
---
```{r echo=F, warning = FALSE, results = 'asis', message = FALSE}

library(knitr)
kable(my_r, align = "lcc")
```  

##### NTC

```{r, echo = F, results='hide',fig.keep='all', warning=F, fig.width=6, fig.height=5.5, fig.align='center'}

plot_list[ntc]

```
\pagebreak

##### PTC

```{r, echo = F,  results='hide',fig.keep='all', warning=F, fig.width=6, fig.height=6.5, fig.align='center'}

plot_list[ptc]

```

\pagebreak
##### CRE


```{r, echo = F,  results='hide',fig.keep='all', warning=F, fig.width=6, fig.height=6.5, fig.align='center'}

plot_list[exc]

```
