---
output: 
  pdf_document:
    keep_tex: false
    fig_caption: yes
    latex_engine: pdflatex
    template: theme/latexTemplate_plate.tex
geometry: left=1.5cm, right=1.5cm, top=6cm
papersize: letterpaper


ninf: "UNIPREC/Covid-19/ 0110"
pname: "`r pname`"
date: "`r Sys.time()`"
classification: "`r classification`"

birthday: "día/mes/año"


fontfamily: fontenc
fontsize: 11pt
header-includes:
   - \linespread{1.05}
graphics: true
width: 1
logoposition: center
logo: theme/Inmegenlogosalud.pdf
---
\pagebreak

```{r echo=F, warning = FALSE, results = 'asis', message = FALSE}

library(knitr)
library(kableExtra)
kable(my_table, row.names = FALSE, 
			col.names = c("Clave","Gen E (Ct)", "Gen RdRp (Ct)", "Gen Rp (Ct)", "Resultado", "Observaciones"), 
			align = "lccccc",
			escape = FALSE) %>%
			column_spec(1, border_left = TRUE) %>% 
			column_spec(6, border_right = TRUE, width = "4cm") %>%
			row_spec(0,bold=TRUE) %>%
			kable_styling("bordered", position = "center") %>%
			add_footnote("S/A = Sin amplificación", notation = "none")
```  

```{r , message = FALSE, echo = F, results='hide', results='asis', eval=sum(!(test.results$classification %in% "negativo")) >= 1, warning=F}
cat("\\pagebreak")
```  

```{r , message = FALSE, echo = F, results='asis', eval=sum(!(test.results$classification %in% "negativo")) >= 1, warning=F}
cat("\\textbf{Anexo.} Curvas $\\Delta\\mathrm{Rn}$ vs. número de ciclo para la detección de los genes E, RdRp y Rp para la(s) muestra(s) donde hubo señal de amplificación.")
```  
\vspace{0.5cm}

```{r , message = FALSE, echo = F, results='hide', eval=sum(!(test.results$classification %in% "negativo")) >= 1, warning=F, fig.width=6, fig.height=6, fig.align='center'}

plot_list[which(!(result_table$classification %in% "negativo"))]
```

